steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/kubernetes-417417/kubernetes/container2:latest',
      '-f',
      'dockerfile', 
      '.',
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/kubernetes-417417/kubernetes/container2:latest']
 
images:
- 'us-central1-docker.pkg.dev/kubernetes-417417/kubernetes/container2:latest'